name: quickstart
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4

  win32: 5.5.1
  web: 1.0.0
  thermion_flutter: ^0.2.1-dev.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  thermion_dart:
    path: /Users/nickfisher/Documents/polyvox/apps/packages/thermion/thermion_dart
  thermion_flutter_web:
    path: /Users/nickfisher/Documents/polyvox/apps/packages/thermion/thermion_flutter/thermion_flutter_web
  thermion_flutter:
    path: /Users/nickfisher/Documents/polyvox/apps/packages/thermion/thermion_flutter/thermion_flutter
  thermion_flutter_platform_interface:
    path: /Users/nickfisher/Documents/polyvox/apps/packages/thermion/thermion_flutter/thermion_flutter_platform_interface
  thermion_flutter_ffi:
    path: /Users/nickfisher/Documents/polyvox/apps/packages/thermion/thermion_flutter/thermion_flutter_ffi

flutter:
  uses-material-design: true
  assets:
    - assets/
