name: thermion_flutter_ffi
description: An FFI interface for the thermion_flutter plugin (all platforms except web).
repository: https://github.com/nmfisher/thermion_flutter/thermion_flutter
version: 0.2.1-dev.6

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"
flutter:
  plugin:
    implements: thermion_flutter_platform_interface
    platforms:
      ios:
        dartPluginClass: ThermionFlutterTextureBackedPlatform
      android:
        dartPluginClass: ThermionFlutterTextureBackedPlatform
      macos:
        dartPluginClass: ThermionFlutterTextureBackedPlatform
      windows:
        dartPluginClass: ThermionFlutterWindows
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  thermion_flutter_platform_interface: ^0.2.1-dev.6
  thermion_dart: ^0.2.1-dev.0.0.7
  logging: ^1.2.0

dependency_overrides:
  thermion_dart:
    path: ../../thermion_dart
  thermion_flutter_platform_interface:
    path: ../thermion_flutter_platform_interface
dev_dependencies:

  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
